#! /bin/bash
set -ex
BASENAME=$(basename "$0")
export CONAN_COLOR_DARK=1

eval $(f0cal env activate -a)

conan install red_eye_demo/0.1@f0cal/testing --build=missing
conan install f0cal-opencv/4.0.1@f0cal/testing --build=missing


f0cal pr add --  removeRedEyes --image=$VIRTUAL_ENV/etc/redeye/red_eyes.jpg --cascade=$VIRTUAL_ENV/etc/redeye/haarcascade_eye.xml

f0cal pr list
f0cal pr view

